const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
function load(file,mocks={}){const exports={},absolute=path.resolve(file),req=name=>{if(name in mocks)return mocks[name];if(!name.startsWith('.')&&!name.startsWith('@/'))return require(name);const target=name.startsWith('@/')?path.resolve('src',name.slice(2)):path.resolve(path.dirname(absolute),name);return load(target.endsWith('.ts')?target:target+'.ts',mocks);};const js=ts.transpileModule(fs.readFileSync(absolute,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;vm.runInNewContext(js,{exports,require:req,process,URL,URLSearchParams,Request,Response,Date,console});return exports;}
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
function fixture(){let user=null,seq=0;const artifacts=new Map(),plays=new Map(),users=new Map([['user-a',{id:'user-a',username:'나',avatarUrl:null}],['user-b',{id:'user-b',username:'친구',avatarUrl:null}]]);
const artifact={findUnique:async({where})=>artifacts.get(where.id)??null,findFirst:async({where})=>[...artifacts.values()].find(row=>row.type===where.type&&row.contentUrl===where.contentUrl)??null,upsert:async({where,create})=>{if(!artifacts.has(where.id))artifacts.set(where.id,{createdAt:new Date(),...create});return artifacts.get(where.id);}};
const matches=(row,where)=>row.artifactId===(where.artifactId??row.artifactId)&&row.userId===(typeof where.userId==='string'?where.userId:row.userId)&&row.score===(typeof where.score==='number'?where.score:row.score)&&(!where.createdAt||row.createdAt>=where.createdAt.gte);
const create=async({data})=>{const row={id:'play-'+(++seq),createdAt:new Date(),...data};plays.set(row.id,row);return row;};
const gamePlay={create,upsert:async({where,create:data})=>plays.get(where.id)??create({data}),groupBy:async({where})=>{const groups=new Map();for(const row of plays.values()){if(row.score<=0||!row.userId||!matches(row,where))continue;const key=row.artifactId+row.userId,old=groups.get(key);if(!old||old._max.score<row.score)groups.set(key,{artifactId:row.artifactId,userId:row.userId,_max:{score:row.score}});}return [...groups.values()];},findFirst:async({where})=>{const row=[...plays.values()].filter(row=>matches(row,where)).sort((a,b)=>a.createdAt-b.createdAt)[0];return row?{...row,user:users.get(row.userId),artifact:artifacts.get(row.artifactId)}:null;}};
const db={artifact,gamePlay,profile:{findFirst:async()=>({id:'admin'})}};const mocks={'@/lib/db':{db},'@/lib/auth':{HttpError,getSessionUser:async()=>user}};
return{artifacts,plays,auth:id=>user=id?{id,role:'user'}:null,api:load('src/app/api/game-room/play/route.ts',mocks),ranking:load('src/app/api/game-room/leaderboard/route.ts',mocks),rules:load('src/lib/server/game-records.ts',mocks)};}
const request=body=>new Request('https://playlab.test/api/game-room/play',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const score=(n,id='round-12345678')=>({artifactId:'builtin-fruit-atelier',score:n,roundId:id,durationMs:12000});const data=async r=>(await r.json()).data;
test('shipped fruit game creates its ranking record on the first authenticated score',async()=>{const f=fixture();f.auth('user-a');const result=await data(await f.api.POST(request(score(430))));assert.equal(result.recorded,true);assert.equal(result.score,430);assert.equal(f.artifacts.size,1);assert.equal(f.plays.size,1);const rankings=await data(await f.ranking.GET(new Request('https://playlab.test/api/game-room/leaderboard?gameId=builtin-fruit-atelier&period=all')));assert.equal(rankings.rankings[0].rank,1);assert.equal(rankings.rankings[0].score,430);assert.equal(rankings.rankings[0].username,'나');});
test('retrying one round is idempotent and cannot replace the score',async()=>{const f=fixture();f.auth('user-a');await f.api.POST(request(score(500)));const result=await data(await f.api.POST(request(score(900))));assert.equal(f.plays.size,1);assert.equal(result.score,500);});
test('leaderboard takes each player best once and numerically orders them',async()=>{const f=fixture();f.auth('user-a');await f.api.POST(request(score(100,'round-11111111')));await f.api.POST(request(score(600,'round-22222222')));await f.api.POST(request(score(200,'round-33333333')));f.auth('user-b');await f.api.POST(request(score(400,'round-44444444')));const result=await data(await f.ranking.GET(new Request('https://playlab.test/api/game-room/leaderboard?gameId=builtin-fruit-atelier&period=all')));assert.equal(result.rankings.length,2);assert.deepEqual(result.rankings.map(p=>p.score),[600,400]);assert.deepEqual(result.rankings.map(p=>p.rank),[1,2]);});
test('anonymous scores and invalid or non-game targets never write rankings',async()=>{const f=fixture();assert.equal((await f.api.POST(request(score(100)))).status,401);f.auth('user-a');for(const value of [-1,1.5,100000001,'100'])assert.equal((await f.api.POST(request({...score(100),score:value}))).status,400);assert.equal((await f.api.POST(request({...score(100),durationMs:-1}))).status,400);assert.equal((await f.api.POST(request({...score(100),artifactId:'unknown'}))).status,404);f.artifacts.set('bad',{id:'bad',type:'image',status:'published',visibility:'public'});assert.equal((await f.api.POST(request({...score(100),artifactId:'bad'}))).status,404);assert.equal(f.plays.size,0);});
test('existing registered IDs are reused and unpublished games cannot be revived by a score',async()=>{const f=fixture();f.artifacts.set('legacy-id',{id:'legacy-id',title:'과일 아틀리에',type:'game',contentUrl:'/games/fruit-atelier.html',status:'published',visibility:'public'});f.auth('user-a');assert.equal((await data(await f.api.POST(request(score(700))))).gameId,'legacy-id');assert.equal(f.artifacts.size,1);f.artifacts.get('legacy-id').status='hidden';assert.equal((await f.api.POST(request(score(800,'round-hidden12')))).status,404);assert.equal(f.plays.size,1);});
test('Korean calendar boundaries use midnight, Monday and month start',()=>{const {rules}=fixture(),now=new Date('2026-10-06T15:05:00Z');assert.equal(rules.periodStart('today',now).toISOString(),'2026-10-06T15:00:00.000Z');assert.equal(rules.periodStart('week',now).toISOString(),'2026-10-04T15:00:00.000Z');assert.equal(rules.periodStart('month',now).toISOString(),'2026-09-30T15:00:00.000Z');});
