import type { RunpodVideoEngine } from '@/lib/server/runpod';
import { H3_PRESETS, h3Size, type H3Preset } from '@/lib/h3-presets';

export type VideoAspectRatio = '9:16' | '16:9' | '1:1';

export interface VideoRenderInput {
  prompt: string;
  durationSec: number;
  aspectRatio: VideoAspectRatio;
  firstFrameName?: string;
  /** Legacy quality fallback; explicit administrator preset takes precedence. */
  quality?: 'draft' | 'standard';
  h3Preset?: H3Preset;
  preview?: boolean;
  seed?: number;
  /** Server-owned administrator comparison, never an arbitrary client size. */
  comparison?: boolean;
}

/** Compatibility export: all LTX callers use the verified 2B workflow. */
export { buildLtx2bWorkflow as buildLtxTextToVideoWorkflow } from './ltx-2b-workflow';

/** API-format workflow generated by the deployed `playlab-h3-test` endpoint. */
export function buildH3TextToVideoWorkflow(input: VideoRenderInput): Record<string, unknown> {
  const { width, height } = h3Size(input.aspectRatio, input.preview);
  const preset = H3_PRESETS[input.h3Preset ?? (input.quality === 'standard' ? 'standard20' : 'turbo8')];
  const prompt = input.prompt.trim().slice(0, 4000);
  return {
    '92': { inputs: { video: ['152', 0], filename_prefix: 'video/MiniMax_H3', format: 'auto', 'format.codec': 'auto' }, class_type: 'SaveVideo', _meta: { title: 'SaveVideo' } },
    '141': { inputs: { vae_name: 'minimax_h3_video_vae_fp16.safetensors' }, class_type: 'VAELoader', _meta: { title: 'VAELoader' } },
    '142': { inputs: { vae_name: 'minimax_h3_audio_vae_fp32.safetensors' }, class_type: 'VAELoader', _meta: { title: 'VAELoader' } },
    '143': { inputs: { samples: ['147', 0], vae: ['142', 0] }, class_type: 'VAEDecodeAudio', _meta: { title: 'VAEDecodeAudio' } },
    '144': { inputs: { samples: ['147', 0], vae: ['141', 0] }, class_type: 'VAEDecode', _meta: { title: 'VAEDecode' } },
    '145': { inputs: { sampler_name: 'res_multistep' }, class_type: 'KSamplerSelect', _meta: { title: 'KSamplerSelect' } },
    '146': { inputs: { model: ['157', 0], steps: ['158', 0], scheduler: 'simple', denoise: 1 }, class_type: 'BasicScheduler', _meta: { title: 'BasicScheduler' } },
    '147': { inputs: { noise: ['151', 0], guider: ['148', 0], sampler: ['145', 0], sigmas: ['146', 0], latent_image: ['153', 1] }, class_type: 'SamplerCustomAdvanced', _meta: { title: 'SamplerCustomAdvanced' } },
    '148': { inputs: { model: ['157', 0], conditioning: ['153', 0] }, class_type: 'BasicGuider', _meta: { title: 'BasicGuider' } },
    '149': { inputs: { unet_name: 'minimax_h3_fl2va_pruned_int8_convrot.safetensors', weight_dtype: 'default' }, class_type: 'UNETLoader', _meta: { title: 'UNETLoader' } },
    '150': { inputs: { clip_name: 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors', type: 'minimax', device: 'default' }, class_type: 'CLIPLoader', _meta: { title: 'CLIPLoader' } },
    '151': { inputs: { noise_seed: input.seed ?? Math.floor(Math.random() * 2_147_483_647) }, class_type: 'RandomNoise', _meta: { title: 'RandomNoise' } },
    // H3 can synthesize audio as well as video. The studio's first-shot flow is
    // intentionally silent unless we add a dedicated audio direction UI, so do
    // not attach its generated audio stream to the rendered file.
    '152': { inputs: { images: ['144', 0], fps: 24, bit_depth: 8, color_space: 'sRGB' }, class_type: 'CreateVideo', _meta: { title: 'CreateVideo' } },
    '153': { inputs: { clip: ['150', 0], vae: ['141', 0], width: ['162', 0], height: ['163', 0], length: ['154', 1], prompt, ...(input.firstFrameName ? { first_frame: ['164', 0] } : {}) }, class_type: 'MiniMaxH3ImageToVideo', _meta: { title: 'MiniMaxH3ImageToVideo' } },
    '154': { inputs: { 'values.a': ['155', 0], expression: 'max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17' }, class_type: 'ComfyMathExpression', _meta: { title: 'Frame Count' } },
    '155': { inputs: { value: Math.max(4, Math.min(15, Math.round(input.durationSec))) }, class_type: 'PrimitiveFloat', _meta: { title: 'Duration' } },
    '156': { inputs: { model: ['149', 0], lora_name: 'minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors', strength_model: 1 }, class_type: 'LoraLoaderModelOnly', _meta: { title: 'LoraLoaderModelOnly' } },
    '157': { inputs: { on_false: ['149', 0], on_true: ['156', 0], switch: ['161', 0] }, class_type: 'ComfySwitchNode', _meta: { title: 'If/Else Switch (Model)' } },
    '158': { inputs: { on_false: ['159', 0], on_true: ['160', 0], switch: ['161', 0] }, class_type: 'ComfySwitchNode', _meta: { title: 'If/Else Switch (Steps)' } },
    '159': { inputs: { value: preset.steps }, class_type: 'PrimitiveInt', _meta: { title: 'Standard steps' } },
    '160': { inputs: { value: 8 }, class_type: 'PrimitiveInt', _meta: { title: 'Turbo steps' } },
    // Turbo and base sampling paths must switch together with the preset.
    '161': { inputs: { value: preset.turbo }, class_type: 'PrimitiveBoolean', _meta: { title: 'Enable Lightning LoRA' } },
    '162': { inputs: { value: width }, class_type: 'PrimitiveInt', _meta: { title: 'Width' } },
    '163': { inputs: { value: height }, class_type: 'PrimitiveInt', _meta: { title: 'Height' } },
    ...(input.firstFrameName ? { '164': { inputs: { image: input.firstFrameName }, class_type: 'LoadImage', _meta: { title: 'First frame' } } } : {}),
  };
}

export function getEngineForFirstShot(inputMode: string, quality?: string): RunpodVideoEngine | null {
  if (inputMode !== 'text' && inputMode !== 'image') return null;
  return quality === 'standard' ? 'h3' : 'ltx';
}
