import type { RunpodVideoEngine } from '@/lib/server/runpod';

export type VideoAspectRatio = '9:16' | '16:9' | '1:1';

export interface VideoRenderInput {
  prompt: string;
  durationSec: number;
  aspectRatio: VideoAspectRatio;
  firstFrameName?: string;
}

function ltxFrameCount(durationSec: number) {
  // LTX accepts frame counts in 8n + 1. At 24 fps this keeps the requested
  // 6–8 second shots close to their intended duration without a silent clamp.
  const requested = Math.max(4, Math.min(15, Math.round(durationSec))) * 24;
  return Math.ceil((requested - 1) / 8) * 8 + 1;
}

function ltxDimensions(aspectRatio: VideoAspectRatio) {
  switch (aspectRatio) {
    case '9:16': return { width: 576, height: 1024 };
    case '1:1': return { width: 768, height: 768 };
    default: return { width: 1024, height: 576 };
  }
}

/**
 * API-format workflow generated by Runpod's ComfyUI wizard for the deployed
 * `ltx2-t2v-distilled` endpoint. Only safe user-controlled fields are varied.
 */
export function buildLtxTextToVideoWorkflow(input: VideoRenderInput): Record<string, unknown> {
  const { width, height } = ltxDimensions(input.aspectRatio);
  const frameCount = ltxFrameCount(input.durationSec);
  const prompt = input.prompt.trim().slice(0, 4000);

  return {
    '104': { inputs: { video: ['197', 0], filename_prefix: 'video/LTX-2', format: 'auto', 'format.codec': 'auto' }, class_type: 'SaveVideo', _meta: { title: 'SaveVideo' } },
    '181': { inputs: { ckpt_name: 'ltx-2-19b-distilled.safetensors' }, class_type: 'LTXVAudioVAELoader', _meta: { title: 'LTXVAudioVAELoader' } },
    '182': { inputs: { clip: ['216', 0], text: ['212', 0] }, class_type: 'CLIPTextEncode', _meta: { title: 'enhanced prompt (positive)' } },
    '183': { inputs: { positive: ['182', 0], negative: ['182', 0], frame_rate: ['209', 0] }, class_type: 'LTXVConditioning', _meta: { title: 'LTXVConditioning' } },
    '184': { inputs: { audio_vae: ['181', 0], frames_number: ['207', 0], frame_rate: ['208', 0], batch_size: 25 }, class_type: 'LTXVEmptyLatentAudio', _meta: { title: 'LTXVEmptyLatentAudio' } },
    '185': { inputs: { width: ['211', 0], height: ['211', 1], length: ['207', 0], batch_size: 1 }, class_type: 'EmptyLTXVLatentVideo', _meta: { title: 'EmptyLTXVLatentVideo' } },
    '186': { inputs: { image: ['210', 0], upscale_method: 'nearest-exact', scale_by: 0.5 }, class_type: 'ImageScaleBy', _meta: { title: 'ImageScaleBy' } },
    '188': { inputs: { ckpt_name: 'ltx-2-19b-distilled.safetensors' }, class_type: 'CheckpointLoaderSimple', _meta: { title: 'CheckpointLoaderSimple' } },
    '189': { inputs: { model: ['188', 0], positive: ['183', 0], negative: ['183', 1], cfg: 1 }, class_type: 'CFGGuider', _meta: { title: 'CFGGuider' } },
    '190': { inputs: { sampler_name: 'euler_ancestral' }, class_type: 'KSamplerSelect', _meta: { title: 'KSamplerSelect' } },
    '191': { inputs: { sigmas: '1., 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0' }, class_type: 'ManualSigmas', _meta: { title: 'ManualSigmas' } },
    '192': { inputs: { sigmas: '0.909375, 0.725, 0.421875, 0.0' }, class_type: 'ManualSigmas', _meta: { title: 'ManualSigmas' } },
    '193': { inputs: { sampler_name: 'euler_ancestral' }, class_type: 'KSamplerSelect', _meta: { title: 'KSamplerSelect' } },
    '194': { inputs: { model: ['188', 0], positive: ['183', 0], negative: ['183', 1], cfg: 1 }, class_type: 'CFGGuider', _meta: { title: 'CFGGuider' } },
    '195': { inputs: { noise_seed: Math.floor(Math.random() * 2_147_483_647) }, class_type: 'RandomNoise', _meta: { title: 'RandomNoise' } },
    '196': { inputs: { video_latent: ['198', 0], audio_latent: ['199', 1] }, class_type: 'LTXVConcatAVLatent', _meta: { title: 'LTXVConcatAVLatent' } },
    '197': { inputs: { images: ['203', 0], audio: ['204', 0], fps: ['209', 0], bit_depth: 8, color_space: 'sRGB' }, class_type: 'CreateVideo', _meta: { title: 'CreateVideo' } },
    '198': { inputs: { samples: ['199', 0], upscale_model: ['215', 0], vae: ['188', 2] }, class_type: 'LTXVLatentUpsampler', _meta: { title: 'LTXVLatentUpsampler' } },
    '199': { inputs: { av_latent: ['213', 1] }, class_type: 'LTXVSeparateAVLatent', _meta: { title: 'LTXVSeparateAVLatent' } },
    '201': { inputs: { noise_seed: Math.floor(Math.random() * 2_147_483_647) }, class_type: 'RandomNoise', _meta: { title: 'RandomNoise' } },
    '203': { inputs: { samples: ['205', 0], vae: ['188', 2], tile_size: 512, overlap: 64, temporal_size: 4096, temporal_overlap: 8 }, class_type: 'VAEDecodeTiled', _meta: { title: 'VAEDecodeTiled' } },
    '204': { inputs: { samples: ['205', 1], audio_vae: ['181', 0] }, class_type: 'LTXVAudioVAEDecode', _meta: { title: 'LTXVAudioVAEDecode' } },
    '205': { inputs: { av_latent: ['214', 1] }, class_type: 'LTXVSeparateAVLatent', _meta: { title: 'LTXVSeparateAVLatent' } },
    '206': { inputs: { video_latent: ['185', 0], audio_latent: ['184', 0] }, class_type: 'LTXVConcatAVLatent', _meta: { title: 'LTXVConcatAVLatent' } },
    '207': { inputs: { value: frameCount }, class_type: 'PrimitiveInt', _meta: { title: 'Frame Count' } },
    '208': { inputs: { value: 24 }, class_type: 'PrimitiveInt', _meta: { title: 'Frame Rate (Int)' } },
    '209': { inputs: { value: 24 }, class_type: 'PrimitiveFloat', _meta: { title: 'Frame Rate (Float)' } },
    '210': { inputs: { width, height, batch_size: 1, color: 0 }, class_type: 'EmptyImage', _meta: { title: 'EmptyImage' } },
    '211': { inputs: { image: ['186', 0] }, class_type: 'GetImageSize', _meta: { title: 'GetImageSize' } },
    '212': { inputs: { value: prompt }, class_type: 'PrimitiveStringMultiline', _meta: { title: 'Positive prompt' } },
    '213': { inputs: { noise: ['201', 0], guider: ['189', 0], sampler: ['190', 0], sigmas: ['191', 0], latent_image: ['206', 0] }, class_type: 'SamplerCustomAdvanced', _meta: { title: 'SamplerCustomAdvanced' } },
    '214': { inputs: { noise: ['195', 0], guider: ['194', 0], sampler: ['193', 0], sigmas: ['192', 0], latent_image: ['196', 0] }, class_type: 'SamplerCustomAdvanced', _meta: { title: 'SamplerCustomAdvanced' } },
    '215': { inputs: { model_name: 'ltx-2-spatial-upscaler-x2-1.0.safetensors' }, class_type: 'LatentUpscaleModelLoader', _meta: { title: 'LatentUpscaleModelLoader' } },
    '216': { inputs: { text_encoder: 'gemma_3_12B_it_fp4_mixed.safetensors', ckpt_name: 'ltx-2-19b-distilled.safetensors', device: 'default' }, class_type: 'LTXAVTextEncoderLoader', _meta: { title: 'LTXAVTextEncoderLoader' } },
  };
}

/** API-format workflow generated by the deployed `playlab-h3-test` endpoint. */
export function buildH3TextToVideoWorkflow(input: VideoRenderInput): Record<string, unknown> {
  const { width, height } = input.aspectRatio === '9:16'
    // Keep the initial render at the Wizard's ~0.4 MP target. The previous
    // 1.03 MP portrait input combined with the standard 20-step sampler hit
    // Runpod's 10-minute job limit before a 6-second preview could finish.
    ? { width: 480, height: 832 }
    : input.aspectRatio === '1:1' ? { width: 640, height: 640 } : { width: 832, height: 480 };
  const prompt = input.prompt.trim().slice(0, 4000);
  return {
    '92': { inputs: { video: ['152', 0], filename_prefix: 'video/MiniMax_H3', format: 'auto', 'format.codec': 'auto' }, class_type: 'SaveVideo', _meta: { title: 'SaveVideo' } },
    '141': { inputs: { vae_name: 'minimax_h3_video_vae_fp16.safetensors' }, class_type: 'VAELoader', _meta: { title: 'VAELoader' } },
    '142': { inputs: { vae_name: 'minimax_h3_audio_vae_fp32.safetensors' }, class_type: 'VAELoader', _meta: { title: 'VAELoader' } },
    '143': { inputs: { samples: ['147', 0], vae: ['142', 0] }, class_type: 'VAEDecodeAudio', _meta: { title: 'VAEDecodeAudio' } },
    '144': { inputs: { samples: ['147', 0], vae: ['141', 0] }, class_type: 'VAEDecode', _meta: { title: 'VAEDecode' } },
    '145': { inputs: { sampler_name: 'res_multistep' }, class_type: 'KSamplerSelect', _meta: { title: 'KSamplerSelect' } },
    '146': { inputs: { model: ['157', 0], steps: ['158', 0], scheduler: 'simple', denoise: 1 }, class_type: 'BasicScheduler', _meta: { title: 'BasicScheduler' } },
    '147': { inputs: { noise: ['151', 0], guider: ['148', 0], sampler: ['145', 0], sigmas: ['146', 0], latent_image: ['153', 1] }, class_type: 'SamplerCustomAdvanced', _meta: { title: 'SamplerCustomAdvanced' } },
    '148': { inputs: { model: ['157', 0], conditioning: ['153', 0] }, class_type: 'BasicGuider', _meta: { title: 'BasicGuider' } },
    '149': { inputs: { unet_name: 'minimax_h3_fl2va_pruned_int8_convrot.safetensors', weight_dtype: 'default' }, class_type: 'UNETLoader', _meta: { title: 'UNETLoader' } },
    '150': { inputs: { clip_name: 'qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors', type: 'minimax', device: 'default' }, class_type: 'CLIPLoader', _meta: { title: 'CLIPLoader' } },
    '151': { inputs: { noise_seed: Math.floor(Math.random() * 2_147_483_647) }, class_type: 'RandomNoise', _meta: { title: 'RandomNoise' } },
    '152': { inputs: { images: ['144', 0], audio: ['143', 0], fps: 24, bit_depth: 8, color_space: 'sRGB' }, class_type: 'CreateVideo', _meta: { title: 'CreateVideo' } },
    '153': { inputs: { clip: ['150', 0], vae: ['141', 0], width: ['162', 0], height: ['163', 0], length: ['154', 1], prompt, ...(input.firstFrameName ? { first_frame: ['164', 0] } : {}) }, class_type: 'MiniMaxH3ImageToVideo', _meta: { title: 'MiniMaxH3ImageToVideo' } },
    '154': { inputs: { 'values.a': ['155', 0], expression: 'max(5, round(a * 24)) + (5 - (max(5, round(a * 24)) % 17)) % 17' }, class_type: 'ComfyMathExpression', _meta: { title: 'Frame Count' } },
    '155': { inputs: { value: Math.max(4, Math.min(15, Math.round(input.durationSec))) }, class_type: 'PrimitiveFloat', _meta: { title: 'Duration' } },
    '156': { inputs: { model: ['149', 0], lora_name: 'minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors', strength_model: 1 }, class_type: 'LoraLoaderModelOnly', _meta: { title: 'LoraLoaderModelOnly' } },
    '157': { inputs: { on_false: ['149', 0], on_true: ['156', 0], switch: ['161', 0] }, class_type: 'ComfySwitchNode', _meta: { title: 'If/Else Switch (Model)' } },
    '158': { inputs: { on_false: ['159', 0], on_true: ['160', 0], switch: ['161', 0] }, class_type: 'ComfySwitchNode', _meta: { title: 'If/Else Switch (Steps)' } },
    '159': { inputs: { value: 20 }, class_type: 'PrimitiveInt', _meta: { title: 'Standard steps' } },
    '160': { inputs: { value: 6 }, class_type: 'PrimitiveInt', _meta: { title: 'Turbo steps' } },
    // The H3 Wizard ships this LoRA for preview throughput: 6 steps instead
    // of 20. High-quality rerenders can be added as an explicit later option.
    '161': { inputs: { value: true }, class_type: 'PrimitiveBoolean', _meta: { title: 'Enable Lightning LoRA' } },
    '162': { inputs: { value: width }, class_type: 'PrimitiveInt', _meta: { title: 'Width' } },
    '163': { inputs: { value: height }, class_type: 'PrimitiveInt', _meta: { title: 'Height' } },
    ...(input.firstFrameName ? { '164': { inputs: { image: input.firstFrameName }, class_type: 'LoadImage', _meta: { title: 'First frame' } } } : {}),
  };
}

export function getEngineForFirstShot(inputMode: string, quality?: string): RunpodVideoEngine | null {
  // The active LTX deployment is text-to-video. Image and frame modes remain
  // explicitly unavailable until their H3/Wan API workflows are captured.
  if (inputMode === 'image') return 'h3';
  if (inputMode !== 'text') return null;
  return quality === 'standard' || quality === 'hero' ? 'h3' : 'ltx';
}
