import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeft,
  Bell,
  Box,
  Check,
  ChevronDown,
  ChevronRight,
  Clapperboard,
  Clock,
  CreditCard,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  FileText,
  Flag,
  FlaskConical,
  FolderKanban,
  Gamepad2,
  GraduationCap,
  Heart,
  Home,
  Images,
  LayoutPanelLeft,
  LoaderCircle,
  LogOut,
  MessageCircle,
  Moon,
  PenLine,
  Play,
  Plus,
  Radar,
  RefreshCw,
  Search,
  Settings,
  Shield,
  Sparkles,
  Star,
  Store,
  Sun,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Users,
  Wallet,
  Wand2,
  Workflow,
  X,
  Zap,
} from 'lucide-react';
import { cn } from '@/lib/utils';

// Static icon map — string keys match MODULE_CONFIGS / QUICK_ACTIONS / shell usage (CONTRACTS §6).
// Unknown names fall back to Sparkles so a bad registry entry never crashes the UI.
const ICON_MAP = {
  home: Home,
  'folder-kanban': FolderKanban,
  images: Images,
  'flask-conical': FlaskConical,
  workflow: Workflow,
  radar: Radar,
  wallet: Wallet,
  store: Store,
  users: Users,
  'graduation-cap': GraduationCap,
  shield: Shield,
  'pen-line': PenLine,
  box: Box,
  clapperboard: Clapperboard,
  'layout-panel-left': LayoutPanelLeft,
  'gamepad-2': Gamepad2,
  heart: Heart,
  eye: Eye,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  search: Search,
  plus: Plus,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  sparkles: Sparkles,
  'wand-2': Wand2,
  'credit-card': CreditCard,
  trophy: Trophy,
  'message-circle': MessageCircle,
  play: Play,
  download: Download,
  star: Star,
  zap: Zap,
  'file-text': FileText,
  upload: Upload,
  'log-out': LogOut,
  settings: Settings,
  'trash-2': Trash2,
  flag: Flag,
  check: Check,
  x: X,
  'arrow-left': ArrowLeft,
  'external-link': ExternalLink,
  'refresh-cw': RefreshCw,
  clock: Clock,
  target: Target,
  'trend-up': TrendingUp,
  'trend-down': TrendingDown,
  ellipsis: Ellipsis,
  'loader-circle': LoaderCircle,
} as const;

export type IconName = keyof typeof ICON_MAP;

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = (ICON_MAP as Record<string, LucideIcon>)[name] ?? Sparkles;
  return <Cmp className={cn('size-4 shrink-0', className)} aria-hidden="true" />;
}
