'use client';

import { useEffect, useState } from 'react';
import { Copy, Download, Loader2, Play, Sparkles } from 'lucide-react';
import QRCode from 'qrcode';

const voices = ['Charon', 'Fenrir', 'Puck', 'Orus', 'Enceladus', 'Kore', 'Aoede', 'Leda', 'Zephyr', 'Callirrhoe'];
const labels: Record<string, string> = { Charon: '차분한 남성', Fenrir: '에너지 있는 남성', Puck: '친근한 남성', Orus: '설명형 남성', Enceladus: '부드러운 남성', Kore: '맑은 여성', Aoede: '따뜻한 여성', Leda: '전문적인 여성', Zephyr: '경쾌한 여성', Callirrhoe: '고급스러운 여성' };

function pcmToWav(base64: string) {
  const binary = atob(base64); const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index++) bytes[index] = binary.charCodeAt(index);
  const pcm = new Int16Array(bytes.buffer); const buffer = new ArrayBuffer(44 + pcm.byteLength); const view = new DataView(buffer);
  const write = (offset: number, value: string) => [...value].forEach((char, index) => view.setUint8(offset + index, char.charCodeAt(0)));
  write(0, 'RIFF'); view.setUint32(4, 36 + pcm.byteLength, true); write(8, 'WAVE'); write(12, 'fmt '); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, 24000, true); view.setUint32(28, 48000, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); write(36, 'data'); view.setUint32(40, pcm.byteLength, true); new Int16Array(buffer, 44).set(pcm);
  return new Blob([buffer], { type: 'audio/wav' });
}
function ErrorBox({ text }: { text: string }) { return text ? <p className="mt-4 rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{text}</p> : null; }

function TtsTool() {
  const [text, setText] = useState('안녕하세요. PLAYLAB AI Tools에서 자연스러운 AI 음성을 만들어 보세요.'); const [voice, setVoice] = useState('Charon'); const [url, setUrl] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]);
  async function generate(preview = false) {
    setLoading(true); setError('');
    try { const response = await fetch('/api/tools/tts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: preview ? '안녕하세요. 이 음성의 분위기와 발음을 미리 들어보세요.' : text, voice }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); const next = URL.createObjectURL(pcmToWav(data.audioBase64)); if (preview) { const player = new Audio(next); player.onended = () => URL.revokeObjectURL(next); await player.play(); } else setUrl((current) => { if (current) URL.revokeObjectURL(current); return next; }); } catch (caught) { setError(caught instanceof Error ? caught.message : '음성 생성에 실패했습니다.'); } finally { setLoading(false); }
  }
  return <section className="mt-10 rounded-2xl border bg-card p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-bold">TTS 메이커</h2><p className="mt-1 text-sm text-muted-foreground">텍스트를 Gemini 음성으로 만들고 WAV 파일로 내려받습니다.</p></div><button onClick={() => generate(true)} disabled={loading} className="inline-flex items-center gap-2 rounded-md border px-4 py-2 text-sm font-medium"><Play className="h-4 w-4" />음성 미리듣기</button></div><textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={10000} rows={9} className="mt-6 w-full rounded-lg border bg-background p-4 text-sm leading-7" /><div className="mt-4 flex flex-wrap gap-2">{voices.map((item) => <button key={item} onClick={() => setVoice(item)} className={`rounded-full border px-3 py-2 text-sm ${voice === item ? 'border-primary bg-primary text-primary-foreground' : 'bg-background'}`}>{item} · {labels[item]}</button>)}</div><button onClick={() => generate()} disabled={loading || !text.trim()} className="mt-5 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{loading ? '생성 중…' : '음성 만들기'}</button><ErrorBox text={error} />{url && <div className="mt-5 rounded-xl bg-muted p-4"><audio className="w-full" controls src={url} /><a download="playlab-tts.wav" href={url} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-primary"><Download className="h-4 w-4" />WAV 다운로드</a></div>}</section>;
}

type Message = { role: 'user' | 'assistant'; content: string };
function MetaPromptTool() {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [result, setResult] = useState<{ finalPrompt: string; domain: string; reasoning: string } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function send() { if (!input.trim() || loading || result) return; const next = [...messages, { role: 'user' as const, content: input.trim() }]; setMessages(next); setInput(''); setLoading(true); setError(''); try { const generate = next.filter((message) => message.role === 'user').length >= 5; const response = await fetch('/api/tools/metaprompt', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: next, mode: generate ? 'generate' : 'question' }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); if (generate) setResult(data); else setMessages([...next, { role: 'assistant', content: data.question }]); } catch (caught) { setError(caught instanceof Error ? caught.message : '생성에 실패했습니다.'); } finally { setLoading(false); } }
  return <section className="mt-10 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-2xl font-bold">메타 프롬프트</h2><p className="mt-1 text-sm text-muted-foreground">목적을 말하면 AI가 필요한 질문을 이어서 묻고, 다섯 번째 답변 뒤 완성 프롬프트를 만듭니다.</p><div className="mt-5 space-y-3 rounded-xl bg-muted/50 p-4">{messages.length === 0 && <p className="text-sm text-muted-foreground">예: “제주 감성의 카페 포스터를 만들고 싶어”</p>}{messages.map((message, index) => <div key={index} className={`max-w-[88%] rounded-xl p-3 text-sm ${message.role === 'user' ? 'ml-auto bg-primary text-primary-foreground' : 'bg-background border'}`}>{message.content}</div>)}{loading && <p className="text-sm text-muted-foreground">생각 중…</p>}</div>{result ? <div className="mt-5 rounded-xl border border-primary/30 bg-primary/5 p-5"><p className="text-sm font-semibold text-primary">{result.domain}</p><pre className="mt-3 whitespace-pre-wrap font-sans text-sm leading-7">{result.finalPrompt}</pre><button onClick={() => navigator.clipboard.writeText(result.finalPrompt)} className="mt-4 inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><Copy className="h-4 w-4" />복사</button></div> : <div className="mt-4 flex gap-2"><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); send(); } }} placeholder="원하는 결과를 설명해 주세요" rows={2} className="flex-1 rounded-lg border bg-background p-3 text-sm" /><button onClick={send} disabled={loading || !input.trim()} className="rounded-md bg-primary px-5 text-sm font-semibold text-primary-foreground">보내기</button></div>}<ErrorBox text={error} /></section>;
}

function SunoTool() {
  const [idea, setIdea] = useState('비 오는 제주 밤, 드라이브하며 듣는 몽환적인 시티팝'); const [result, setResult] = useState<{ title: string; genre: string; mood: string; stylePrompt: string; lyrics: string } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function create() { setLoading(true); setError(''); try { const response = await fetch('/api/tools/suno', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ idea }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : '음악 프롬프트 생성에 실패했습니다.'); } finally { setLoading(false); } }
  return <section className="mt-10 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-2xl font-bold">Suno 뮤직 메이커</h2><p className="mt-1 text-sm text-muted-foreground">한 줄 아이디어로 Suno용 스타일 프롬프트, 제목, 완성 가사를 만듭니다.</p><textarea value={idea} onChange={(event) => setIdea(event.target.value)} rows={4} className="mt-5 w-full rounded-lg border bg-background p-4 text-sm" /><button onClick={create} disabled={loading || !idea.trim()} className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{loading ? '작곡 기획 중…' : 'Suno 프롬프트 만들기'}</button><ErrorBox text={error} />{result && <div className="mt-5 grid gap-4"><div className="rounded-xl bg-muted p-4"><p className="font-bold">{result.title} <span className="ml-2 text-sm font-normal text-muted-foreground">{result.genre} · {result.mood}</span></p></div><Output title="Suno Style of Music" value={result.stylePrompt} /><Output title="Lyrics" value={result.lyrics} /></div>}</section>;
}
function QrTool() {
  const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [image, setImage] = useState(''); const [error, setError] = useState('');
  async function create() {
    setError('');
    try {
      const raw = address.trim(); const url = /^https?:\/\//i.test(raw) ? raw : `https://${raw}`; new URL(url);
      setImage(await QRCode.toDataURL(url, { width: 900, margin: 2, color: { dark: '#111827', light: '#ffffff' } }));
    } catch { setError('유효한 웹 주소를 입력해 주세요.'); }
  }
  return <section className="mt-10 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-2xl font-bold">QR 코드 생성기</h2><p className="mt-1 text-sm text-muted-foreground">웹 주소를 QR 코드 PNG로 즉시 생성하고 내려받습니다.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={address} onChange={(event) => setAddress(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && create()} placeholder="https://example.com" className="rounded-lg border bg-background px-3 py-3 text-sm" /><input value={name} onChange={(event) => setName(event.target.value)} placeholder="파일 이름 (선택)" className="rounded-lg border bg-background px-3 py-3 text-sm" /></div><button onClick={create} disabled={!address.trim()} className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground"><Sparkles className="size-4" />QR 코드 만들기</button><ErrorBox text={error} />{image && <div className="mt-6 flex flex-col items-center rounded-xl bg-muted p-6"><img src={image} alt="생성된 QR 코드" className="size-56 rounded-lg bg-white p-2" /><a href={image} download={`${name.trim() || 'playlab-qrcode'}.png`} className="mt-4 inline-flex items-center gap-2 rounded-md border bg-background px-4 py-2 text-sm font-semibold"><Download className="size-4" />PNG 다운로드</a></div>}</section>;
}
function ThumbnailTool() {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [audience, setAudience] = useState(''); const [mood, setMood] = useState(''); const [result, setResult] = useState<{ hook: string; overlayText: string; imagePrompt: string; composition: string; colorDirection: string; avoid: string[] } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function create() { setLoading(true); setError(''); try { const response = await fetch('/api/tools/thumbnail', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, audience, mood }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setResult(data); } catch (caught) { setError(caught instanceof Error ? caught.message : '생성에 실패했습니다.'); } finally { setLoading(false); } }
  return <section className="mt-10 rounded-2xl border bg-card p-6 shadow-sm"><h2 className="text-2xl font-bold">유튜브 썸네일 메이커</h2><p className="mt-1 text-sm text-muted-foreground">콘텐츠 정보를 바탕으로 CTR을 고려한 문구·구도·이미지 생성 프롬프트를 만듭니다.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="영상 제목" className="rounded-lg border bg-background px-3 py-3 text-sm" /><input value={audience} onChange={(event) => setAudience(event.target.value)} placeholder="주 시청자 (선택)" className="rounded-lg border bg-background px-3 py-3 text-sm" /></div><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="영상에서 전달할 핵심 내용" rows={4} className="mt-3 w-full rounded-lg border bg-background p-3 text-sm" /><input value={mood} onChange={(event) => setMood(event.target.value)} placeholder="원하는 분위기·브랜드 컬러 (선택)" className="mt-3 w-full rounded-lg border bg-background px-3 py-3 text-sm" /><button onClick={create} disabled={loading || !title.trim() || !description.trim()} className="mt-4 inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 font-semibold text-primary-foreground">{loading ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}{loading ? '분석 중…' : '썸네일 기획 만들기'}</button><ErrorBox text={error} />{result && <div className="mt-5 grid gap-3 sm:grid-cols-2"><Output title="클릭 포인트" value={`${result.hook}\n\n오버레이 문구: ${result.overlayText}\n구도: ${result.composition}\n색상: ${result.colorDirection}`} /><Output title="이미지 생성 프롬프트" value={result.imagePrompt} /><Output title="피할 요소" value={result.avoid.join(', ')} /></div>}</section>;
}
function Output({ title, value }: { title: string; value: string }) { return <div className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{title}</h3><button onClick={() => navigator.clipboard.writeText(value)} className="text-sm text-primary">복사</button></div><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap font-sans text-sm leading-7 text-muted-foreground">{value}</pre></div>; }

export function ToolExperience({ slug }: { slug: string }) { if (slug === 'tts') return <TtsTool />; if (slug === 'metaprompt') return <MetaPromptTool />; if (slug === 'suno') return <SunoTool />; if (slug === 'qr') return <QrTool />; if (slug === 'thumbnail') return <ThumbnailTool />; return null; }
